### ISSUE TITLE
Similar Projects

### ISSUE THREAD

**Issue by Lutzifer** [LinusU/RasterizeXCAssets#1]
I just found out about this project via the https://github.com/yonasKolb/Mint Readme.

We have a very similar tool (https://github.com/num42/icon-resizer-swift) that specialises in creating AppIcons.

So far I know of these project:

https://github.com/num42/icon-resizer-swift - Creates the AppIcons
https://github.com/LinusU/RasterizeXCAssets - Creates Assets from SVGs
https://github.com/jkmathew/Assetizer - Creates Assets, but not the AppIcons

Maybe we can pool up resources somehow (or at least mention each others projects in the READMEs).

(See also https://github.com/jkmathew/Assetizer/issues/1)

**Comment by LinusU** [comment]
Awesome, I'll add the links to the Readme right away, would be happy to pool resources in any other way 🙌

**Comment by leogdion** [comment]
👋Hello there! I run [Speculid](https://github.com/brightdigit/Speculid). I would love some collaboration/feedback as well.

**Comment by Lutzifer** [comment]
@leogdion looks interesting, nice!

**Comment by juliangsp** [comment]
Hey folks, seems like this 'issue' can be closed too. Greeting!
