### ISSUE TITLE
Error: Failed to resolve RasterizeXCAssets 1.0.0-alpha.2 with SPM

### ISSUE THREAD

**Issue by juliangsp** [LinusU/RasterizeXCAssets#3]
When installing (via Mint), I get "Failed to resolve RasterizeXCAssets 1.0.0-alpha.2 with SPM". Seems like a sub-dependency issue with PromiseKit:

```
$ mint install LinusU/RasterizeXCAssets
🌱 Finding latest version of RasterizeXCAssets
🌱 Cloning RasterizeXCAssets 1.0.0-alpha.2
🌱 Resolving package
https://github.com/mxcl/PromiseKit @ 6.2.2: error: invalidManifestFormat("/var/folders/md/d0c2cx454gjdhmbyrfjj6tww0000gn/T/TemporaryFile.4pP5aL.swift:25:30: error: cannot convert value of type \'Int\' to expected element type \'Array<SwiftVersion>.ArrayLiteralElement\' (aka \'SwiftVersion\')\npkg.swiftLanguageVersions = [3, 4]\n                             ^\n/var/folders/md/d0c2cx454gjdhmbyrfjj6tww0000gn/T/TemporaryFile.4pP5aL.swift:25:33: error: cannot convert value of type \'Int\' to expected element type \'Array<SwiftVersion>.ArrayLiteralElement\' (aka \'SwiftVersion\')\npkg.swiftLanguageVersions = [3, 4]\n                                ^", diagnosticFile: nil) in https://github.com/mxcl/PromiseKit
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve RasterizeXCAssets 1.0.0-alpha.2 with SPM
```

**Comment by LinusU** [comment]
Interesting. This is the line where our dependency on PromiseKit is introduced:

https://github.com/LinusU/JSBridge/blob/cb5846a525a31c79f7040fd9df024438883d8924/Package.swift#L11

It seems straight forward to me 🤔 

Version 6.2.2 of PromiseKit is quite old though, it seems like it's using this file to decide the versions:

https://github.com/LinusU/RasterizeXCAssets/blob/master/Package.resolved

Could probably just update that and it should work hopefully. Let's try!

**Comment by LinusU** [comment]
@juliangsp could you try the command again, which should pick up version `1.0.0-alpha.3`?

**Comment by juliangsp** [comment]
`$ mint install LinusU/RasterizeXCAssets
🌱 Finding latest version of RasterizeXCAssets
🌱 Cloning RasterizeXCAssets 1.0.0-alpha.3
🌱 Resolving package
🌱 Building package
🌱 Installed RasterizeXCAssets 1.0.0-alpha.3
🌱 Linked rasterizexcassets 1.0.0-alpha.3 to /Users/jgsp/.mint/bin`

now it works! 🎉  problem solved, thanks @LinusU !
